serialized_models_path: "./serialized_models" # carpeta donde estan todos los modelos (NO CAMBIAR)
campaigns_filepath: "./archivos_insumo/archivo_insumo_2023.csv" # Directorio donde esta el archivo de insumo de campa単as
prior_year_sales_file_path: "./datasets/historico_ventas_2023_semanal.csv" # Historico de ventas del a単o ANTERIOR al que se hara la prediccion (si se desea obtener prediccion para el a単o 2024, se debera tener el historico de ventas del 2023 - desde enero hasta diciembre -)
year_to_forecast: 2024 # a単o que se hara la prediccion
